### GET ALL ENTRIES
GET {{host}}/{{requestmapping}}
Content-Type: application/json

### GET ALL ENTRIES
GET {{host}}/{{requestmapping}}/search
Content-Type: application/json

{
  "appId": null,
  "context": null,
  "textId": null,
  "stage": "ACC"
}

### POST NEW ENTRY
POST {{host}}/{{requestmapping}}
Content-Type: application/json

{
  "appId": "OPC",
  "textId": "com.axa.ch.sgpc.opc.features",
  "content": "OPC-ADMIN",
  "stage": "ACC",
  "german": "Auf Wiedersehen",
  "english": "Goodbye",
  "french": "Au revoir",
  "italian": "Arrivederci"
}

### UPDATE ENTRY
PUT {{host}}/{{requestmapping}}/2
Content-Type: application/json

{
  "id": "2",
  "appId": "OPC",
  "textId": "com.axa.ch.sgpc.opc.features",
  "content": "OPC-ADMIN",
  "stage": "DEV",
  "german": "Hallo",
  "english": "Hello",
  "french": "Bonjour",
  "italian": "Buongiorno",
  "translated": true,
  "lastModified": null
}

### DELETE ENTRY
DELETE {{host}}/{{requestmapping}}/2